spring.application.name=invoicing-service

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true


spring.profiles.active=${ACTIVE_PROFILE:dev}
server.port=${SERVER_PORT:8082}
server.servlet.context-path=/api/v1

spring.grpc.server.enabled=true
spring.grpc.server.port=9090
spring.grpc.server.address=0.0.0.0