spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://localhost:5433/invoice-db
spring.datasource.username=admin
spring.datasource.password= kxOTkxZTk1YjhkNzg0MTYqAi7muRWttDl6AkJFoo