spring:
  application:
    name: patient-service

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  profiles:
    active: ${ACTIVE_PROFILE:dev}



server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api